### ISSUE TITLE
multiprocessing error

### ISSUE THREAD

**Issue by y-hwang** [MrOlm/inStrain#101]
Hi Matt, 

when running instrain profile I run into this error, and the job gets stuck. Could you help me figure out what's wrong? Thanks!

Command I am running is as follows: 

inStrain profile -p 20 -l 0.94 -s genomes.stb -g combined.genes.fna -o inStrain.$i bamfiles/drep.$i.sorted.bam combined.fasta

and the error I get stuck with: 

Merging splits and profiling genes:  35%|███▌      | 44/124 [12:02<11:39,  8.75s/it]Process SpawnProcess-52:
Traceback (most recent call last):
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py", line 382, in merge_profile_worker
    Sprofile = Sprofile.update_splits(i, Sprofile_dict.pop(
  File "<string>", line 2, in pop
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process SpawnProcess-44:
Traceback (most recent call last):
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py", line 382, in merge_profile_worker
    Sprofile = Sprofile.update_splits(i, Sprofile_dict.pop(
  File "<string>", line 2, in pop
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process SpawnProcess-48:
Traceback (most recent call last):
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py", line 382, in merge_profile_worker
    Sprofile = Sprofile.update_splits(i, Sprofile_dict.pop(
  File "<string>", line 2, in pop
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process SpawnProcess-57:
Traceback (most recent call last):
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py", line 382, in merge_profile_worker
    Sprofile = Sprofile.update_splits(i, Sprofile_dict.pop(
  File "<string>", line 2, in pop
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process SpawnProcess-46:
Traceback (most recent call last):
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py", line 382, in merge_profile_worker
    Sprofile = Sprofile.update_splits(i, Sprofile_dict.pop(
  File "<string>", line 2, in pop
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process SpawnProcess-61:
Traceback (most recent call last):
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py", line 382, in merge_profile_worker
    Sprofile = Sprofile.update_splits(i, Sprofile_dict.pop(
  File "<string>", line 2, in pop
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process SpawnProcess-59:
Traceback (most recent call last):
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py", line 382, in merge_profile_worker
    Sprofile = Sprofile.update_splits(i, Sprofile_dict.pop(
  File "<string>", line 2, in pop
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process SpawnProcess-55:
Traceback (most recent call last):
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py", line 382, in merge_profile_worker
    Sprofile = Sprofile.update_splits(i, Sprofile_dict.pop(
  File "<string>", line 2, in pop
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process SpawnProcess-58:
Traceback (most recent call last):
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py", line 382, in merge_profile_worker
    Sprofile = Sprofile.update_splits(i, Sprofile_dict.pop(
  File "<string>", line 2, in pop
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process SpawnProcess-60:
Traceback (most recent call last):
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py", line 382, in merge_profile_worker
    Sprofile = Sprofile.update_splits(i, Sprofile_dict.pop(
  File "<string>", line 2, in pop
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process SpawnProcess-49:
Traceback (most recent call last):
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py", line 382, in merge_profile_worker
    Sprofile = Sprofile.update_splits(i, Sprofile_dict.pop(
  File "<string>", line 2, in pop
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process SpawnProcess-42:
Traceback (most recent call last):
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py", line 382, in merge_profile_worker
    Sprofile = Sprofile.update_splits(i, Sprofile_dict.pop(
  File "<string>", line 2, in pop
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process SpawnProcess-43:
Traceback (most recent call last):
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py", line 382, in merge_profile_worker
    Sprofile = Sprofile.update_splits(i, Sprofile_dict.pop(
  File "<string>", line 2, in pop
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process SpawnProcess-50:
Traceback (most recent call last):
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py", line 382, in merge_profile_worker
    Sprofile = Sprofile.update_splits(i, Sprofile_dict.pop(
  File "<string>", line 2, in pop
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process SpawnProcess-45:
Traceback (most recent call last):
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py", line 382, in merge_profile_worker
    Sprofile = Sprofile.update_splits(i, Sprofile_dict.pop(
  File "<string>", line 2, in pop
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process SpawnProcess-56:
Traceback (most recent call last):
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py", line 382, in merge_profile_worker
    Sprofile = Sprofile.update_splits(i, Sprofile_dict.pop(
  File "<string>", line 2, in pop
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process SpawnProcess-54:
Traceback (most recent call last):
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py", line 382, in merge_profile_worker
    Sprofile = Sprofile.update_splits(i, Sprofile_dict.pop(
  File "<string>", line 2, in pop
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process SpawnProcess-51:
Traceback (most recent call last):
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py", line 382, in merge_profile_worker
    Sprofile = Sprofile.update_splits(i, Sprofile_dict.pop(
  File "<string>", line 2, in pop
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process SpawnProcess-53:
Traceback (most recent call last):
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py", line 382, in merge_profile_worker
    Sprofile = Sprofile.update_splits(i, Sprofile_dict.pop(
  File "<string>", line 2, in pop
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process SpawnProcess-47:
Traceback (most recent call last):
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py", line 382, in merge_profile_worker
    Sprofile = Sprofile.update_splits(i, Sprofile_dict.pop(
  File "<string>", line 2, in pop
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Merging splits and profiling genes:  36%|███▋      | 45/124 [12:21<15:32, 11.81s/it]

**Comment by MrOlm** [comment]
Hello,

I've never encountered this error before, and in googling around I don't see anything about what could be causing it. InStrain on my hardware with python 3.8 works fine. My thoughts are:

1) This could be caused by the machine running out of RAM, which can cause all sorts of weird error messages. Try increasing RAM if you can, or decreasing the number of processes used (more process = more RAM)

2) This could be caused by an outdated dependency; maybe try "pip install instrain --upgrade" to update all dependencies

3) If we can't get to the bottom of this, running with one thread (`-p 1`) bypasses multiprocessing altogether so you will definitely not get this error.

Best,
Matt

**Comment by y-hwang** [comment]
Hi Matt, thanks for the suggestions.
I increased the allocated memory and it seems to have solved this particular error. 
BUT, now the program has been stuck at "merging splits and profiling genes" for about couple days. And I checked the RAM usage and that does not seem to be the problem. 

Here is the last part of the output:
Profiling splits: 100%|█████████▉| 5131/5136 [2:38:03<00:11,  2.32s/it][W::hts_idx_load3] The index file is older than the data file: bamfiles/drep.c8.sorted.bam.bai
Profiling splits: 100%|█████████▉| 5133/5136 [2:38:04<00:04,  1.37s/it][W::hts_idx_load3] The index file is older than the data file: bamfiles/drep.c8.sorted.bam.bai
Profiling splits: 100%|█████████▉| 5135/5136 [2:38:05<00:00,  1.29it/s][W::hts_idx_load3] The index file is older than the data file: bamfiles/drep.c8.sorted.bam.bai
Profiling splits: 100%|██████████| 5136/5136 [2:38:06<00:00,  1.85s/it]
Merging splits and profiling genes: 100%|██████████| 134/134 [51:39<00:00, 23.13s/it]

and the tail of log/log.log:

WorkerLog MergeProfile NODE_93187_length_2464_cov_7.172686 end 4693843968 1646705872.1792636 15922
22-03-07 21:18:16 DEBUG
WorkerLog MergeProfile NODE_93188_length_2464_cov_6.984641 start 4693843968 1646705872.2410212 15922
WorkerLog MergeProfile NODE_93188_length_2464_cov_6.984641 end 4693843968 1646705872.2791884 15922
22-03-07 21:18:16 DEBUG
WorkerLog MergeProfile NODE_93189_length_2464_cov_6.095475 start 4693843968 1646705872.3450627 15922
WorkerLog MergeProfile NODE_93189_length_2464_cov_6.095475 end 4693843968 1646705872.43021 15922

GroupLog MergeProfile 15922_7 start 3939049472 1646705304.9008074 15922 overall
GroupLog MergeProfile 15922_7 end 4693843968 1646705872.5679624 15922 overall

Do you have an idea what might be happening here? Thanks!
