### ISSUE TITLE
Tutorial 1 comparison error

### ISSUE THREAD

**Issue by iwilkie** [MrOlm/inStrain#107]
Hi @MrOlm,

I plan on using inStrain for a project I'm working on, and thought that I would start with the tutorial detailed in the inStrain documentation. Specifically, I'm following [tutorial number 1 on the provided test data](https://instrain.readthedocs.io/en/latest/tutorial.html#tutorial-1-running-instrain-on-provided-test-data). 

I successfully managed to generate the two profiles (that is `N5_271_010G1_scaffoled_min1000.fa-vs-N5_271_010G1.IS` and `N5_271_010G1_scaffoled_min1000.fa-vs-N5_271_010G2.IS`), but when I try to compare the two using `inStrain compare` I get a message which states that there are no shared scaffolds among the IS. I've included the outputs for the two profiling and the comparison step below. 

I initially thought that this might be due to the tutorial suggesting the use of two different input file types for the two profiles (there the commands include a `.sam` file when generating the first profile and a `.sorted.bam` file for the second one), but I still get this message when using `.sorted.bam` files for both profiles. 

I'm probably just missing a very obvious step (could it be an issue with the installation?), but don't really know where to go from here. I tried looking through past issues/googling this error but have not found any similar problems. Any help would be greatly appreciated, thank you in advance!

<p>
<details>
<summary> Outputs for the three steps (generating two profiles and running the comparison): </summary>

```bash
(bioinf) iwilkie@lin-desk-10-6:~/inStrain_test/01.testing_tutorial$ inStrain profile \
> test_data/N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G1.sorted.bam \
> test_data/N5_271_010G1_scaffold_min1000.fa \
> -o N5_271_010G1_scaffoled_min1000.fa-vs-N5_271_010G1.IS \
> -p 6 \
> -g test_data/N5_271_010G1_scaffold_min1000.fa.genes.fna \
> -s test_data/N5_271_010G1.maxbin2.stb

***************************************************
    ..:: inStrain profile Step 1. Filter reads ::..
***************************************************
        
Filtering reads: 100%|██████████████████████████████████████████████████████████████████████| 178/178 [00:09<00:00, 17.99it/s]
62.8% of reads were removed during filtering
7,179 read pairs remain (0.001819 Gbp)
***************************************************
.:: inStrain profile Step 2. Profile scaffolds ::..
***************************************************
        
Profiling splits: 100%|█████████████████████████████████████████████████████████████████████████| 7/7 [00:21<00:00,  3.06s/it]
Merging splits and profiling genes: 100%|███████████████████████████████████████████████████████| 7/7 [00:23<00:00,  3.38s/it]
***************************************************
.:: inStrain profile Step 4. Make genome-wide ::..
***************************************************
        
Scaffold to bin was made using .stb file
87.69% of scaffolds have a genome
93.82% of scaffolds have a genome
73.52% of scaffolds have a genome
***************************************************
 .:: inStrain profile Step 5. Generate plots ::..
***************************************************
        
making plots 1, 2, 3, 4, 5, 6, 7, 8, 9
Plotting plot 1
Plotting plot 2
87.69% of scaffolds have a genome
Plotting plot 3
73.44% of scaffolds have a genome
Plotting plot 4
67.13% of scaffolds have a genome
Plotting plot 5
Plotting plot 6
Plotting plot 7
67.13% of scaffolds have a genome
Plotting plot 8
94.32% of scaffolds have a genome
Plotting plot 9
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

..:: inStrain profile finished ::..

Output tables........ /home/iwilkie/inStrain_test/01.testing_tutorial/N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G1.IS/output/
Figures.............. /home/iwilkie/inStrain_test/01.testing_tutorial/N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G1.IS/figures/
Logging.............. /home/iwilkie/inStrain_test/01.testing_tutorial/N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G1.IS/log/

See documentation for output descriptions - https://instrain.readthedocs.io/en/latest/

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

(bioinf) iwilkie@lin-desk-10-6:~/inStrain_test/01.testing_tutorial$ inStrain profile \
> test_data/N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G2.sorted.bam \
> test_data/N5_271_010G1_scaffold_min1000.fa \
> -o N5_271_010G1_scaffoled_min1000.fa-vs-N5_271_010G2.IS \
> -p 6 \
> -g test_data/N5_271_010G1_scaffold_min1000.fa.genes.fna \
> -s test_data/N5_271_010G1.maxbin2.stb

***************************************************
    ..:: inStrain profile Step 1. Filter reads ::..
***************************************************
        
Filtering reads: 100%|██████████████████████████████████████████████████████████████████████| 178/178 [00:04<00:00, 38.08it/s]
58.8% of reads were removed during filtering
9,435 read pairs remain (0.002411 Gbp)
***************************************************
.:: inStrain profile Step 2. Profile scaffolds ::..
***************************************************
        
Profiling splits: 100%|█████████████████████████████████████████████████████████████████████████| 7/7 [00:23<00:00,  3.30s/it]
Merging splits and profiling genes: 100%|███████████████████████████████████████████████████████| 7/7 [00:17<00:00,  2.49s/it]
***************************************************
.:: inStrain profile Step 4. Make genome-wide ::..
***************************************************
        
Scaffold to bin was made using .stb file
89.50% of scaffolds have a genome
93.82% of scaffolds have a genome
66.13% of scaffolds have a genome
***************************************************
 .:: inStrain profile Step 5. Generate plots ::..
***************************************************
        
making plots 1, 2, 3, 4, 5, 6, 7, 8, 9
Plotting plot 1
Plotting plot 2
89.50% of scaffolds have a genome
Plotting plot 3
74.19% of scaffolds have a genome
Plotting plot 4
63.31% of scaffolds have a genome
Plotting plot 5
Plotting plot 6
Plotting plot 7
63.31% of scaffolds have a genome
Plotting plot 8
94.32% of scaffolds have a genome
Plotting plot 9
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

..:: inStrain profile finished ::..

Output tables........ /home/iwilkie/inStrain_test/01.testing_tutorial/N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G2.IS/output/
Figures.............. /home/iwilkie/inStrain_test/01.testing_tutorial/N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G2.IS/figures/
Logging.............. /home/iwilkie/inStrain_test/01.testing_tutorial/N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G2.IS/log/

See documentation for output descriptions - https://instrain.readthedocs.io/en/latest/

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

(bioinf) iwilkie@lin-desk-10-6:~/inStrain_test/01.testing_tutorial$ inStrain compare \
> -i N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G1.IS/ \
> N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G2.IS/ \
> -s .N5_271_010G1.maxbin2.stb \
> -p 6 \
> -o N5_271_010G1_scaffold_min1000.fa.IS.COMPARE

Loading N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G1.IS/
Loading N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G2.IS/
178 of 178 scaffolds are in at least 2 samples
0 of these scaffolds are in the provided list of 167
Traceback (most recent call last):
  File "/home/iwilkie/miniconda3/envs/bioinf/bin/inStrain", line 31, in <module>
    inStrain.controller.Controller().main(args)
  File "/home/iwilkie/miniconda3/envs/bioinf/lib/python3.7/site-packages/inStrain/controller.py", line 44, in main
    self.compare_operation(args)
  File "/home/iwilkie/miniconda3/envs/bioinf/lib/python3.7/site-packages/inStrain/controller.py", line 70, in compare_operation
    inStrain.readComparer.main(args)
  File "/home/iwilkie/miniconda3/envs/bioinf/lib/python3.7/site-packages/inStrain/readComparer.py", line 38, in main
    RCprof, names, Sprofiles, scaffolds_to_compare, outbase, s2l = parse_validate(args)
  File "/home/iwilkie/miniconda3/envs/bioinf/lib/python3.7/site-packages/inStrain/readComparer.py", line 306, in parse_validate
    assert len(scaffolds_to_compare) > 0, "No scaffolds are shared amoung the IS"
AssertionError: No scaffolds are shared amoung the IS
```

**Comment by MrOlm** [comment]
Hi @iwilkie ,

Thanks for reaching out with this! I definitely want to make sure that the tutorial on the website is working.

From my reading of the logs, it seems like the problem is with the `.stb` file. I'm thinking this because of the `inStrain compare` log stating that `178 of 178 scaffolds are in at least 2 samples
0 of these scaffolds are in the provided list of 167`

Could you please check a couple things-

1) Try running without the `.stb` file and make sure it works; the rest of the command can stay the same

2) It looks like in other runs the `.stb` file was provided from another folder (e.g. `test_data/N5_271_010G1.maxbin2.stb`); maybe try moving the file into another folder like that?

Depending on how these two things go we can do some more in depth troubleshooting.

Thanks again,
Matt

**Comment by iwilkie** [comment]
Hi @MrOlm 

Thank you for your quick response and for taking the time to help me out, sorry for the delay on my part. I've tried both of your suggestions, it still doesn't seem to work:

1. Without the `.stb` file
```bash
(bioinf) iwilkie@bigmem-5:~/inStrain_test/01.testing_tutorial$ ls
N5_271_010G1_scaffoled_min1000.fa-vs-N5_271_010G1.IS  N5_271_010G1_scaffoled_min1000.fa-vs-N5_271_010G2.IS  test_data
(bioinf) iwilkie@bigmem-5:~/inStrain_test/01.testing_tutorial$ inStrain compare -i N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G1.IS/ N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G2.IS/ -p 6 -o N5_271_010G1_scaffold_min1000.fa.IS.COMP
ARE
IS N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G1.IS/ does not exist! Skipping
IS N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G2.IS/ does not exist! Skipping
0 of 0 scaffolds are in at least 2 samples
Traceback (most recent call last):
  File "/home/iwilkie/miniconda3/envs/bioinf/bin/inStrain", line 31, in <module>
    inStrain.controller.Controller().main(args)
  File "/home/iwilkie/miniconda3/envs/bioinf/lib/python3.7/site-packages/inStrain/controller.py", line 44, in main
    self.compare_operation(args)
  File "/home/iwilkie/miniconda3/envs/bioinf/lib/python3.7/site-packages/inStrain/controller.py", line 70, in compare_operation
    inStrain.readComparer.main(args)
  File "/home/iwilkie/miniconda3/envs/bioinf/lib/python3.7/site-packages/inStrain/readComparer.py", line 38, in main
    RCprof, names, Sprofiles, scaffolds_to_compare, outbase, s2l = parse_validate(args)
  File "/home/iwilkie/miniconda3/envs/bioinf/lib/python3.7/site-packages/inStrain/readComparer.py", line 306, in parse_validate
    assert len(scaffolds_to_compare) > 0, "No scaffolds are shared amoung the IS"
AssertionError: No scaffolds are shared amoung the IS
```

2. Moving the `.stb` file
```bash
(bioinf) iwilkie@bigmem-5:~/inStrain_test/01.testing_tutorial$ cp test_data/N5_271_010G1.maxbin2.stb .
(bioinf) iwilkie@bigmem-5:~/inStrain_test/01.testing_tutorial$ ls
N5_271_010G1.maxbin2.stb  N5_271_010G1_scaffold_min1000.fa.IS.COMPARE  N5_271_010G1_scaffoled_min1000.fa-vs-N5_271_010G1.IS  N5_271_010G1_scaffoled_min1000.fa-vs-N5_271_010G2.IS  test_data
(bioinf) iwilkie@bigmem-5:~/inStrain_test/01.testing_tutorial$ inStrain compare -i N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G1.IS/ N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G2.IS/ -s N5_271_010G1.maxbin2.stb -p 6 -o N5_271_010G1
_scaffold_min1000.fa.IS.COMPARE
IS N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G1.IS/ does not exist! Skipping
IS N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G2.IS/ does not exist! Skipping
0 of 0 scaffolds are in at least 2 samples
0 of these scaffolds are in the provided list of 167
Traceback (most recent call last):
  File "/home/iwilkie/miniconda3/envs/bioinf/bin/inStrain", line 31, in <module>
    inStrain.controller.Controller().main(args)
  File "/home/iwilkie/miniconda3/envs/bioinf/lib/python3.7/site-packages/inStrain/controller.py", line 44, in main
    self.compare_operation(args)
  File "/home/iwilkie/miniconda3/envs/bioinf/lib/python3.7/site-packages/inStrain/controller.py", line 70, in compare_operation
    inStrain.readComparer.main(args)
  File "/home/iwilkie/miniconda3/envs/bioinf/lib/python3.7/site-packages/inStrain/readComparer.py", line 38, in main
    RCprof, names, Sprofiles, scaffolds_to_compare, outbase, s2l = parse_validate(args)
  File "/home/iwilkie/miniconda3/envs/bioinf/lib/python3.7/site-packages/inStrain/readComparer.py", line 306, in parse_validate
    assert len(scaffolds_to_compare) > 0, "No scaffolds are shared amoung the IS"
AssertionError: No scaffolds are shared amoung the IS
```

**Comment by MrOlm** [comment]
Thanks! For (2), it seems like the paths you provided to the `.IS` folders are off? This is based on the log messages `x does not exist!`.

**Comment by MrOlm** [comment]
Hi @iwilkie - in the failed `compare` run, is the folder `raw_data` created? If so, are the files `scaffold2bin` and `scaffold_list` in there? If so, could you upload them here?

Thank again for your help,
Matt

**Comment by iwilkie** [comment]
@MrOlm So the `raw_data` folder is created but doesn't contain either of the two files that you mentioned, here's the contents

```bash
(bioinf) iwilkie@lin-desk-10-5:~/inStrain_test/01.testing_tutorial/external_scaffold$ ls N5_271_010G1_scaffold_min1000.fa.IS.COMPARE/raw_data/ -l
total 19
-rw-r--r-- 1 iwilkie biogeo 232 Jun 23 19:43 attributes.tsv
-rw-r--r-- 1 iwilkie biogeo 191 Jun 23 19:43 _README.txt
```

**Comment by MrOlm** [comment]
OK- could you please upload 1) the `scaffold2bin` file from the successful `profile` run (either run should work), and 2) the `scaffold_list` file from the the successful `compare` run (where the scaffold to bin file was not included)?

**Comment by iwilkie** [comment]
1. [scaffold2bin.txt](https://github.com/MrOlm/inStrain/files/8974347/scaffold2bin.txt) (I had to convert it to `txt` because GitHub wouldn't let me upload the `json` file)
 2. There is no `scaffold_list` file in the successful `compare` run (this is from the comparison without a scaffold file)... here's the contents of the `raw_data` folder: 
```bash
iwilkie@lin-desk-10-1:~/inStrain_test/01.testing_tutorial/without_scaffold/N5_271_010G1_scaffold_min1000.fa.IS.COMPARE$ ls raw_data/
attributes.tsv  comparisonsTable.csv.gz  scaffold2length.json  _README.txt
```

**Comment by MrOlm** [comment]
OK- I really think this is a problem with the version of inStrain that's installed

What command did you use to install inStrain? I can see that the latest version should be live on conda (https://anaconda.org/bioconda/instrain). Can you report what running:

`conda install -c bioconda instrain --upgrade`

reports?

Thanks,
Matt

**Comment by iwilkie** [comment]
So I installed it 3 weeks ago via `conda install -c conda-forge -c bioconda -c defaults instrain`, which I did after running `conda install -c bioconda samtools`

```bash
iwilkie@lin-desk-10-6:~$ conda activate bioinf
(bioinf) iwilkie@lin-desk-10-6:~$ conda install -c bioconda instrain --upgrade
usage: conda [-h] [-V] command ...
conda: error: unrecognized arguments: --upgrade
(bioinf) iwilkie@lin-desk-10-6:~$ conda update instrain -c bioconda
Collecting package metadata (current_repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 4.13.0

Please update conda by running

    $ conda update -n base conda

## Package Plan ##

  environment location: /home/iwilkie/miniconda3/envs/bioinf

  added / updated specs:
    - instrain

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    colorama-0.4.5             |     pyhd8ed1ab_0          18 KB  conda-forge
    setuptools-scm-7.0.2       |     pyhd8ed1ab_0          34 KB  conda-forge
    typing-extensions-4.2.0    |       hd8ed1ab_1           8 KB  conda-forge
    uncertainties-3.1.7        |     pyhd8ed1ab_0          76 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         136 KB

The following NEW packages will be INSTALLED:

  typing-extensions  conda-forge/noarch::typing-extensions-4.2.0-hd8ed1ab_1

The following packages will be UPDATED:

  colorama                               0.4.4-pyh9f0ad1d_0 --> 0.4.5-pyhd8ed1ab_0
  setuptools-scm                         6.4.2-pyhd8ed1ab_0 --> 7.0.2-pyhd8ed1ab_0
  uncertainties                          3.1.6-pyhd8ed1ab_0 --> 3.1.7-pyhd8ed1ab_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
colorama-0.4.5       | 18 KB     | ################################################################################### | 100% 
typing-extensions-4. | 8 KB      | ################################################################################### | 100% 
uncertainties-3.1.7  | 76 KB     | ################################################################################### | 100% 
setuptools-scm-7.0.2 | 34 KB     | ################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(bioinf) iwilkie@lin-desk-10-6:~$ inStrain --help

                ...::: inStrain v1.3.4 :::...
```

I haven't updated to v4.13.0 of conda yet because I did the update to v4.12.0 recently and had to delete and re-make all of my environments. I guess this is a sign that it's time to update conda again... I'll do that and try upgrading inStrain again and will report the outputs back to you. Thanks again for helping me out!

**Comment by iwilkie** [comment]
Updating conda made no difference: 

```bash
iwilkie@lin-desk-10-6:~$ conda update conda
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/iwilkie/miniconda3

  added / updated specs:
    - conda

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.13.0               |   py37h89c1867_1         989 KB  conda-forge
    libzlib-1.2.12             |       h166bdaf_1          63 KB  conda-forge
    openssl-3.0.4              |       h166bdaf_0         2.8 MB  conda-forge
    pip-22.1.2                 |     pyhd8ed1ab_0         1.5 MB  conda-forge
    readline-8.1.2             |       h0f457ee_0         291 KB  conda-forge
    requests-2.28.0            |     pyhd8ed1ab_0          52 KB  conda-forge
    setuptools-62.6.0          |   py37h89c1867_0         1.3 MB  conda-forge
    zlib-1.2.12                |       h166bdaf_1          91 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         7.2 MB

The following packages will be UPDATED:

  ca-certificates                      2021.10.8-ha878542_0 --> 2022.6.15-ha878542_0
  certifi                          2021.10.8-py37h89c1867_2 --> 2022.6.15-py37h89c1867_0
  colorama                               0.4.4-pyh9f0ad1d_0 --> 0.4.5-pyhd8ed1ab_0
  conda                               4.12.0-py37h89c1867_0 --> 4.13.0-py37h89c1867_1
  libzlib                              1.2.11-h166bdaf_1014 --> 1.2.12-h166bdaf_1
  openssl                                  3.0.3-h166bdaf_0 --> 3.0.4-h166bdaf_0
  pip                                     22.1-pyhd8ed1ab_0 --> 22.1.2-pyhd8ed1ab_0
  readline                                   8.1-h46c0cb4_0 --> 8.1.2-h0f457ee_0
  requests                              2.27.1-pyhd8ed1ab_0 --> 2.28.0-pyhd8ed1ab_0
  ruamel_yaml                     0.15.80-py37h5e8e339_1006 --> 0.15.80-py37h540881e_1007
  setuptools                          62.2.0-py37h89c1867_0 --> 62.6.0-py37h89c1867_0
  zlib                                 1.2.11-h166bdaf_1014 --> 1.2.12-h166bdaf_1


Proceed ([y]/n)? y


Downloading and Extracting Packages
pip-22.1.2           | 1.5 MB    | ################################################################################### | 100% 
requests-2.28.0      | 52 KB     | ################################################################################### | 100% 
zlib-1.2.12          | 91 KB     | ################################################################################### | 100% 
libzlib-1.2.12       | 63 KB     | ################################################################################### | 100% 
readline-8.1.2       | 291 KB    | ################################################################################### | 100% 
setuptools-62.6.0    | 1.3 MB    | ################################################################################### | 100% 
conda-4.13.0         | 989 KB    | ################################################################################### | 100% 
openssl-3.0.4        | 2.8 MB    | ################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

tiwilkie@lin-desk-10-6:~$ conda activate bioinf
(bioinf) iwilkie@lin-desk-10-6:~$ conda update inStrain -c bioconda
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

(bioinf) iwilkie@lin-desk-10-6:~$ inStrain --help

                ...::: inStrain v1.3.4 :::...
```

Would you recommend uninstalling and reinstalling inStrain?

**Comment by MrOlm** [comment]
Awesome- I'm very glad we got this working and thank you for your patience!
