### ISSUE TITLE
inStrain compare key error when SNV Pooling

### ISSUE THREAD

**Issue by szimmerman92** [MrOlm/inStrain#109]
Hi @MrOlm ,

When I was running instrain compare when supplying my bam files with the -bams option I get the error "KeyError: 'A'

The full command I run is below

`inStrain compare -i /n/data1/joslin/icrb/kostic/szimmerman/multigen/instrain_profile_output/mHFD-98/mHFD-98.IS/ /n/data1/joslin/icrb/kostic/szimmerman/multigen/instrain_profile_output/mHFD-150/mHFD-150.IS/ -s data/drep_output_2/rep_genomes.stb -p 1 -o instrain_compare_output/mHFD-98_VS_mHFD-150.COMPARE_dbmode --database_mode -bams /n/data1/joslin/icrb/kostic/szimmerman/multigen/instrain_profile_output/mHFD-98/mHFD-98.sorted.bam /n/data1/joslin/icrb/kostic/szimmerman/multigen/instrain_profile_output/mHFD-150/mHFD-150.sorted.bam` 

However, it works perfectly if I don't include the '-bam' argument.

Below is the error, which occurs during Step 3 of inStrain compare and attached you can find the log file.

Thank you for making such a great tool!

Best,
Sam

***************************************************
..:: inStrain compare Step 3. Auxiliary processing ::..
***************************************************
                
Pulling 196902 SNVs from 1180 scaffolds. This should take ~ 19.7 min in total
Pulling SNVs from BAMs: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1180/1180 [03:54<00:00,  5.04it/s]
Traceback (most recent call last):
  File "/home/sez10/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'A'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sez10/miniconda3_2/envs/instrain/bin/inStrain", line 31, in <module>
    inStrain.controller.Controller().main(args)
  File "/home/sez10/miniconda3_2/envs/instrain/lib/python3.8/site-packages/inStrain/controller.py", line 56, in main
    self.compare_operation(args)
  File "/home/sez10/miniconda3_2/envs/instrain/lib/python3.8/site-packages/inStrain/controller.py", line 85, in compare_operation
    inStrain.compare_controller.CompareController(args).main()
  File "/home/sez10/miniconda3_2/envs/instrain/lib/python3.8/site-packages/inStrain/compare_controller.py", line 73, in main
    self.run_auxillary_processing()
  File "/home/sez10/miniconda3_2/envs/instrain/lib/python3.8/site-packages/inStrain/compare_controller.py", line 298, in run_auxillary_processing
    PM.main()
  File "/home/sez10/miniconda3_2/envs/instrain/lib/python3.8/site-packages/inStrain/polymorpher.py", line 98, in main
    self.make_pooled_SNV_info_table()
  File "/home/sez10/miniconda3_2/envs/instrain/lib/python3.8/site-packages/inStrain/polymorpher.py", line 141, in make_pooled_SNV_info_table
    self.PMdb = generate_pooled_SNV_summary_table(self.DSTdb, self.name2snpTable, self.name2scaffs)
  File "/home/sez10/miniconda3_2/envs/instrain/lib/python3.8/site-packages/inStrain/polymorpher.py", line 507, in generate_pooled_SNV_summary_table
    Ddb['depth'] = Ddb['A'] + Ddb['C'] + Ddb['G'] + Ddb['T']
  File "/home/sez10/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3455, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/sez10/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'A'
[log.log](https://github.com/MrOlm/inStrain/files/9174057/log.log)

**Comment by MrOlm** [comment]
Hi Sam,

Thank you for the bug report. I believe I know what the issue is and I'll make sure I patch it in the next inStrain update. I'll update this issue when the bug is fixed or if I need any other information from you.

Thanks again,
Matt

**Comment by szimmerman92** [comment]
Hi @MrOlm

After doing some debugging I believe I found a fix for the bug. 

I replaced the line of code `Ddb = DDST.groupby(level=[1]).sum()` in the file polymorpher.py (line 506 I believe) with the following code.

Ddb_list = []
index_list = []
`for myindex, indexDF in DDST.groupby(level=[1]):`

> `    Ddb_list.append(indexDF[['A','C','T','G']].sum(axis=0))`


> `    index_list.append(myindex)`

`Ddb = pd.DataFrame(Ddb_list)`
`Ddb = Ddb.set_index(pd.Index(index_list))`
`Ddb['scaffold'] = scaff`

Sorry in advance for the weird block quoting, it was the only way I could figure out how to make indents. I'm not sure why your original code did not work, but this may be a temporary fix for those that need it. I can also make a pull request and push the update if you think this is a good solution.

Thanks for making a great tool, Matt.

Best,
Sam

**Comment by MrOlm** [comment]
This is amazing Sam- thanks for doing this and apologies it's taken me a while to fix the bug myself! I will happily accept a pull request if you have the time to make one (I have a series of automatic tests I will run first to make sure there are no unexpected errors), but otherwise I will implement this solution myself sometime next week.

Thanks again,
Matt

**Comment by szimmerman92** [comment]
Hi Matt,

No problem at all. Thank you. I just submitted a pull request. Feel free to reach out if any of the tests does not seem to work or if you have any other questions.

Best,
Sam
