### ISSUE TITLE
ModuleNotFoundError: No module named 'numba'`

### ISSUE THREAD

**Issue by mcmahon-uw** [MrOlm/inStrain#113]
Hi!
I installed inStrain v.1.6.2 using bioconda and was trying to run profile with the test data (and with my own) but am getting an error that makes me think the numpy dependency isn't working properly. I tried simply re-installing numpy into the conda environment, but conda recognized that it was already installed. Any suggestions? Do you think it's just a conda issue and I should try a different installation approach?

`inStrain profile N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G1.bam N5_271_010G1_scaffold_min1000.fa -o N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G1.IS -p 1 -g N5_271_010G1_scaffold_min1000.fa.genes.fna -s N5_271_010G1.maxbin2.stb
`

Gave me:

`Traceback (most recent call last):
  File "/home/GLBRCORG/trina.mcmahon/miniconda3/envs/instrain/bin/inStrain", line 19, in <module>
    import inStrain.controller
  File "/home/GLBRCORG/trina.mcmahon/miniconda3/envs/instrain/lib/python3.6/site-packages/inStrain/controller.py", line 20, in <module>
    import inStrain.profile
  File "/home/GLBRCORG/trina.mcmahon/miniconda3/envs/instrain/lib/python3.6/site-packages/inStrain/profile/__init__.py", line 5, in <module>
    import inStrain.profile.profile_controller
  File "/home/GLBRCORG/trina.mcmahon/miniconda3/envs/instrain/lib/python3.6/site-packages/inStrain/profile/profile_controller.py", line 13, in <module>
    import inStrain.SNVprofile
  File "/home/GLBRCORG/trina.mcmahon/miniconda3/envs/instrain/lib/python3.6/site-packages/inStrain/SNVprofile.py", line 21, in <module>
    import inStrain.profile.profile_utilities
  File "/home/GLBRCORG/trina.mcmahon/miniconda3/envs/instrain/lib/python3.6/site-packages/inStrain/profile/profile_utilities.py", line 21, in <module>
    from numba import jit
ModuleNotFoundError: No module named 'numba'`

**Comment by mcmahon-uw** [comment]
Actually, I think I was able to solve it. I had to do some extra installations in the conda environment (numba, biopython v1.74, lmfit, and samtools). Not sure why these didn't install properly, but I wanted to report back for anyone else with the same problem!)

**Comment by MrOlm** [comment]
Awesome- I'm glad it was an easy fix and thank you for reporting back how you did it!

Let me know if you run into any more problems

-Matt
