### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'samtools'

### ISSUE THREAD

**Issue by LeahBriscoe** [MrOlm/inStrain#122]
Hello, I successfully installed instrain through pipinstall in my conda 3.9 environment without issue. However, when running the basic inStrain profile command I get the following error

Here is what I ran:

`inStrain profile genomes.bam genomes.fa -o Family19`

here is the output:
```
Indexing genomes.bam
samtools index genomes.bam genomes.bam.bai -@ 6
Traceback (most recent call last):
  File "/u/project/ngarud/briscoel/inStrain/bin/inStrain", line 31, in <module>
    inStrain.controller.Controller().main(args)
  File "/u/project/ngarud/briscoel/inStrain/lib/python3.9/site-packages/inStrain/controller.py", line 53, in main
    self.profile_operation(args)
  File "/u/project/ngarud/briscoel/inStrain/lib/python3.9/site-packages/inStrain/controller.py", line 82, in profile_operation
    ProfileController(args).main()
  File "/u/project/ngarud/briscoel/inStrain/lib/python3.9/site-packages/inStrain/controller.py", line 142, in main
    self.validate_arguments()
  File "/u/project/ngarud/briscoel/inStrain/lib/python3.9/site-packages/inStrain/controller.py", line 185, in validate_arguments
    self.bam = inStrain.profile.samtools_ops.prepare_bam_fie(args.bam, args.processes)
  File "/u/project/ngarud/briscoel/inStrain/lib/python3.9/site-packages/inStrain/profile/samtools_ops.py", line 40, in prepare_bam_fie
    call(cmd)
  File "/u/project/ngarud/briscoel/inStrain/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/u/project/ngarud/briscoel/inStrain/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/u/project/ngarud/briscoel/inStrain/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'samtools'
```

**Comment by MrOlm** [comment]
Hello

samtools is a dependency of inStrain; it needs to be installed in order for inStrain to work 

Best,
Matt

**Comment by LeahBriscoe** [comment]
Thanks for the quick response, I thought for some reason samtools was installed implicitly by pysam
