### ISSUE TITLE
KeyError: 'mm'

### ISSUE THREAD

**Issue by nick-youngblut** [MrOlm/inStrain#13]
I'm using `instrain  1.2.8  (pypi)` and getting the following error when running `inStrain profile`:

```
Traceback (most recent call last):
  File "/ebio/abt3_projects/Anxiety_Twins_Metagenomes/bin/llmgps/.snakemake/conda/c47fe51b/bin/inStrain", line 31, in <module>
    inStrain.controller.Controller().main(args)
  File "/ebio/abt3_projects/Anxiety_Twins_Metagenomes/bin/llmgps/.snakemake/conda/c47fe51b/lib/python3.8/site-packages/inStrain/controller.py", line 32, in main
    self.profile_operation(args)
  File "/ebio/abt3_projects/Anxiety_Twins_Metagenomes/bin/llmgps/.snakemake/conda/c47fe51b/lib/python3.8/site-packages/inStrain/controller.py", line 56, in profile_operation
    ProfileController().main(args)
  File "/ebio/abt3_projects/Anxiety_Twins_Metagenomes/bin/llmgps/.snakemake/conda/c47fe51b/lib/python3.8/site-packages/inStrain/controller.py", line 181, in main
    Controller().profile_genes_operation(args)
  File "/ebio/abt3_projects/Anxiety_Twins_Metagenomes/bin/llmgps/.snakemake/conda/c47fe51b/lib/python3.8/site-packages/inStrain/controller.py", line 65, in profile_genes_operation
    inStrain.GeneProfile.Controller().main(args)
  File "/ebio/abt3_projects/Anxiety_Twins_Metagenomes/bin/llmgps/.snakemake/conda/c47fe51b/lib/python3.8/site-packages/inStrain/GeneProfile.py", line 541, in main
    Gdb = get_gene_info(IS)
  File "/ebio/abt3_projects/Anxiety_Twins_Metagenomes/bin/llmgps/.snakemake/conda/c47fe51b/lib/python3.8/site-packages/inStrain/GeneProfile.py", line 479, in get_gene_info
    db = db[db['mm'] <= mm].sort_values('mm').drop_duplicates(subset=['gene'], keep='last')
  File "/ebio/abt3_projects/Anxiety_Twins_Metagenomes/bin/llmgps/.snakemake/conda/c47fe51b/lib/python3.8/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/ebio/abt3_projects/Anxiety_Twins_Metagenomes/bin/llmgps/.snakemake/conda/c47fe51b/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'mm'
```

I'm guessing that it's due to the fact that the input *.bam file has almost nothing in it, but then it would be good if `instrain profile` exited gracefully, especially since I'm running it in parallel on ~300 samples; some of which complete, and some are dying with this KeyError.

**Comment by MrOlm** [comment]
Hi Nick,

I think you're right about the cause of the problem, and I just pushed a version to fix this (version `1.2.9`). Let me know if the problem persists.

Best,
Matt
