### ISSUE TITLE
Errors for Merging splits and profiling genes

### ISSUE THREAD

**Issue by 473021677** [MrOlm/inStrain#182]
Hi,
    I am trying to run inStrain profile, and the resulting files have been generated. However, some errors have occurred. It shows "
Merging splits and profiling genes:   0%|          | 0/7 [00:00<?, ?it/s]
Merging splits and profiling genes:  14%|█▍        | 1/7 [04:11<25:08, 251.35s/it]
Merging splits and profiling genes:  29%|██▊       | 2/7 [04:31<09:37, 115.45s/it]
Merging splits and profiling genes:  43%|████▎     | 3/7 [05:05<05:12, 78.25s/it] 
Merging splits and profiling genes:  57%|█████▋    | 4/7 [05:13<02:30, 50.27s/it]
Merging splits and profiling genes:  71%|███████▏  | 5/7 [07:53<02:59, 89.87s/it]
Merging splits and profiling genes:  86%|████████▌ | 6/7 [08:03<01:02, 62.77s/it]
Merging splits and profiling genes: 100%|██████████| 7/7 [10:44<00:00, 94.95s/it]
Merging splits and profiling genes: 100%|██████████| 7/7 [10:44<00:00, 92.07s/it]Traceback (most recent call last):
  File "/share/home/linanh2/miniconda3/envs/instrain/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/share/home/linanh2/miniconda3/envs/instrain/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/share/home/linanh2/miniconda3/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 616, in _run_server
    server.serve_forever()
  File "/share/home/linanh2/miniconda3/envs/instrain/lib/python3.8/multiprocessing/managers.py", line 182, in serve_forever
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/home/linanh2/miniconda3/envs/instrain/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/share/home/linanh2/miniconda3/envs/instrain/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/share/home/linanh2/miniconda3/envs/instrain/lib/python3.8/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/share/home/linanh2/miniconda3/envs/instrain/lib/python3.8/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/share/home/linanh2/miniconda3/envs/instrain/lib/python3.8/shutil.py", line 675, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/share/home/linanh2/miniconda3/envs/instrain/lib/python3.8/shutil.py", line 673, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs0000002c008adb7900000f24' " in the nohup.out.txt file.
I do not know what is wrong and am not sure if these errors influence the results. I need your help. I have appended the nohup.out.txt file, the log file and the resulting files. Thanks.

Best regards
[log.log](https://github.com/MrOlm/inStrain/files/15383845/log.log)
[nohup.out.txt](https://github.com/MrOlm/inStrain/files/15383846/nohup.out.txt)
[j9_fl_Sixteen_guangdong_coastal_planktonic_micro_reps.IS_gene_info.txt](https://github.com/MrOlm/inStrain/files/15383853/j9_fl_Sixteen_guangdong_coastal_planktonic_micro_reps.IS_gene_info.txt)
[j9_fl_Sixteen_guangdong_coastal_planktonic_micro_reps.IS_genome_info.txt](https://github.com/MrOlm/inStrain/files/15383854/j9_fl_Sixteen_guangdong_coastal_planktonic_micro_reps.IS_genome_info.txt)
[j9_fl_Sixteen_guangdong_coastal_planktonic_micro_reps.IS_mapping_info.txt](https://github.com/MrOlm/inStrain/files/15383855/j9_fl_Sixteen_guangdong_coastal_planktonic_micro_reps.IS_mapping_info.txt)
[j9_fl_Sixteen_guangdong_coastal_planktonic_micro_reps.IS_scaffold_info.txt](https://github.com/MrOlm/inStrain/files/15383856/j9_fl_Sixteen_guangdong_coastal_planktonic_micro_reps.IS_scaffold_info.txt)

**Comment by MrOlm** [comment]
Hi @473021677 -

Weird. This error seems to be caused by some sort of multiprocessing problem with your filesystem.

The problem seems to be just related to shutting down the multiprocessing after all the real work was finished. Thus, the run seems to have completed successfully with valid results.

Best,
Matt

**Comment by 473021677** [comment]
Thanks for your help.
