### ISSUE TITLE
Local variable 'stb' referenced before assignment

### ISSUE THREAD

**Issue by asierFernandezP** [MrOlm/inStrain#197]
Hi! I have generated the inStrain profiles for my gut vOTUs discovered from gut metagenomic samples (inStrain works well until that step). However when running inStrain compare I get the error shown below. When I remove the --database_mode flag, it seems to run without any problem. Is it possible to specify --breadth 0.75 without using the --database_mode flag? I would like to use that threshold as I am working with viral genomes.

Do I need to create an stb file for this command to work?

My command:

```
inStrain compare \
	  -i $IS_profiles/* \
	  -o 3_INSTRAIN_COMPARISONS \
	  #--database_mode \
	  --breadth 0.75 \
	  --min_cov 5 \
	  --min_freq 0.05 \
	  --fdr 1e-06 \
	  -p ${SLURM_CPUS_PER_TASK} 
```

The error:

```
Traceback (most recent call last):
  File "/scratch/hb-llnext/python_venvs/inStrain/bin/inStrain", line 31, in <module>
    inStrain.controller.Controller().main(args)
  File "/scratch/hb-llnext/python_venvs/inStrain/lib/python3.10/site-packages/inStrain/controller.py", line 57, in main
    self.compare_operation(args)
  File "/scratch/hb-llnext/python_venvs/inStrain/lib/python3.10/site-packages/inStrain/controller.py", line 89, in compare_operation
    inStrain.compare_controller.CompareController(args).main()
  File "/scratch/hb-llnext/python_venvs/inStrain/lib/python3.10/site-packages/inStrain/compare_controller.py", line 47, in main
    self.parse_arguments()
  File "/scratch/hb-llnext/python_venvs/inStrain/lib/python3.10/site-packages/inStrain/compare_controller.py", line 128, in parse_arguments
    for s, b in stb.items():
UnboundLocalError: local variable 'stb' referenced before assignment
```

**Comment by MrOlm** [comment]
Hello,

Thank you for your question and for using inStrain! The error you're encountering is due to the --database_mode flag, which requires an .stb file to function. Without this file, the stb variable isn’t defined, leading to the error.

If you want to use --database_mode and the --breadth argument, create an .stb file mapping scaffolds to bins.

Let me know if you have further questions!

Best,
Matt
