### ISSUE TITLE
Step 2 IndexError: list index out of range

### ISSUE THREAD

**Issue by SergioRLL** [MrOlm/inStrain#38]
Hello, 
I'm running **inStrain profile** specifying the gene file (-g option) and I'm getting this error. Any ideas? I run it previously without the gene file and I didn't get any error. Gene file extension is .fna
Thank you

.:: inStrain profile Step 2. Profile scaffolds ::..
        
Traceback (most recent call last):
  File "/home/srodriguez/.local/bin/inStrain", line 31, in <module>
    inStrain.controller.Controller().main(args)
  File "/home/srodriguez/.local/lib/python3.8/site-packages/inStrain/controller.py", line 50, in main
    self.profile_operation(args)
  File "/home/srodriguez/.local/lib/python3.8/site-packages/inStrain/controller.py", line 76, in profile_operation
    ProfileController(args).main()
  File "/home/srodriguez/.local/lib/python3.8/site-packages/inStrain/controller.py", line 136, in main
    self.run_profile()
  File "/home/srodriguez/.local/lib/python3.8/site-packages/inStrain/controller.py", line 302, in run_profile
    self.ISP = inStrain.profile.profile_bam(self.bam, self.fasta_db,
  File "/home/srodriguez/.local/lib/python3.8/site-packages/inStrain/profile/__init__.py", line 17, in profile_bam
    return inStrain.profile.profile_controller.BamProfileController(
  File "/home/srodriguez/.local/lib/python3.8/site-packages/inStrain/profile/profile_controller.py", line 48, in main
    self.gen_prof_args()
  File "/home/srodriguez/.local/lib/python3.8/site-packages/inStrain/profile/profile_controller.py", line 78, in gen_prof_args
    self.gen_genes_args()
  File "/home/srodriguez/.local/lib/python3.8/site-packages/inStrain/profile/profile_controller.py", line 89, in gen_genes_args
    scaff2geneinfo, scaff2gene2sequence = inStrain.GeneProfile.parse_genes(gene_file, **self.kwargs)
  File "/home/srodriguez/.local/lib/python3.8/site-packages/inStrain/GeneProfile.py", line 754, in parse_genes
    return parse_prodigal_genes(gene_file_loc)
  File "/home/srodriguez/.local/lib/python3.8/site-packages/inStrain/GeneProfile.py", line 781, in parse_prodigal_genes
    table['direction'].append(record.description.split("#")[3].strip())
IndexError: list index out of range

**Comment by MrOlm** [comment]
Hi Sergio,

Sorry for the confusing error. Right now inStrain requires gene calls to be generated by the program Prodigal, as it uses information Prodigal puts in gene headers to parse the genes. This error seems to be happening because you're using genes generated using another source.

Adding more options for specifying genes is on the development "to do" list, however. Would you mind telling me the source of your .fna file so I can try and develop support for that source-type in the future?

Thanks,
Matt

**Comment by SergioRLL** [comment]
The source of the .fna file was Prodigal indeed, however, I believe it was obtained in a different way the InStrain tutorial does it. I ran Prodigal again in that way and it worked.

Thank you,
Sergio

**Comment by MrOlm** [comment]
Great- glad to here this is sorted out

-Matt
