### ISSUE TITLE
inStrain compare KeyError: 'covT' 

### ISSUE THREAD

**Issue by SergioRLL** [MrOlm/inStrain#41]
Hello,

I ran inStrain compare using: `inStrain compare -i XXXX -o YYYY` and got the following error in the first on one of the genomes:
  
Loading Profiles into RAM:   0%|          | 0/4 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/opt/ohpc/pub/apps/python/3.8.5/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2891, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'covT'The above exception was the direct cause of the following exception:Traceback (most recent call last):
  File "/home/srodriguez/.local/bin/inStrain", line 31, in <module>
    inStrain.controller.Controller().main(args)
  File "/home/srodriguez/.local/lib/python3.8/site-packages/inStrain/controller.py", line 53, in main
    self.compare_operation(args)
  File "/home/srodriguez/.local/lib/python3.8/site-packages/inStrain/controller.py", line 79, in compare_operation
    inStrain.compare_controller.CompareController(args).main()
  File "/home/srodriguez/.local/lib/python3.8/site-packages/inStrain/compare_controller.py", line 53, in main
    self.create_scaffoldcomparison_objects()
  File "/home/srodriguez/.local/lib/python3.8/site-packages/inStrain/compare_controller.py", line 162, in create_scaffoldcomparison_objects
    valid_SCs, scaffold2length = make_scaffoldcomparison_objects(self.inputs, scaffolds_to_compare)
  File "/home/srodriguez/.local/lib/python3.8/site-packages/inStrain/compare_controller.py", line 513, in make_scaffoldcomparison_objects
    scaffolds = list(ISP._get_covt_keys())
  File "/home/srodriguez/.local/lib/python3.8/site-packages/inStrain/SNVprofile.py", line 533, in _get_covt_keys
    filename = self.get_location('raw_data') + '/' + os.path.basename(Adb.loc['covT', 'value'])
  File "/opt/ohpc/pub/apps/python/3.8.5/lib/python3.8/site-packages/pandas/core/indexing.py", line 873, in __getitem__
    return self._getitem_tuple(key)
  File "/opt/ohpc/pub/apps/python/3.8.5/lib/python3.8/site-packages/pandas/core/indexing.py", line 1044, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/opt/ohpc/pub/apps/python/3.8.5/lib/python3.8/site-packages/pandas/core/indexing.py", line 786, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/opt/ohpc/pub/apps/python/3.8.5/lib/python3.8/site-packages/pandas/core/indexing.py", line 1110, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/opt/ohpc/pub/apps/python/3.8.5/lib/python3.8/site-packages/pandas/core/indexing.py", line 1059, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/opt/ohpc/pub/apps/python/3.8.5/lib/python3.8/site-packages/pandas/core/generic.py", line 3488, in xs
    loc = self.index.get_loc(key)
  File "/opt/ohpc/pub/apps/python/3.8.5/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2893, in get_loc
    raise KeyError(key) from err
KeyError: 'covT'

However, the rest of the steps ran without errors but only one output was produced (*comparisonsTable.tsv). Is some extra argument or parameter needed?

Thank you,
Sergio

**Comment by SergioRLL** [comment]
**NOTE**: I believe the above error may have been caused due to a lack of RAM mem that I had initially and when I ran it again it also used the previously created folder and interpret it as another profile to be used.

However, I still do not know why the other ones that run correctly produced only one of the outputs neither the plot that are indicated in the documentation.

Sergio

**Comment by MrOlm** [comment]
Hello,

The `"KeyError: 'covT'"` error likely arose because one of the profiles was not made correctly- likely because it ran out of RAM, as you suggest. All properly-made inStrain profile folders should have the file `raw_data/covT` in them, and this error results when that file is not there.

Once that "KeyError" happened, it's not surprising to me that many (but not all) of the the following steps failed. Please let me know if you still have problems when only using properly-made inStrain profile objects in your `compare` command.

Best,
Matt

**Comment by SergioRLL** [comment]
Hello,

There were no errors in the next run I did. However, I only obtained the comparisonsTable.tsv as output again. I am not using the option -s for the scaffold-to-bin file as I am using different fasta files for each of the genomes (bins). For this reason, I previously ran `inStrain profile` without the -s option.

Regards,
Sergio

**Comment by MrOlm** [comment]
Hi Sergio,

May I ask which output file you're looking for besides `comparisonsTable.tsv`? In order to get `genomeWide_compare.tsv` and/or `strain_clusters.tsv`, you'll need to provide a .stb file.  Can you explain again why you are unable to provide an .stb file in your use-case?

Best,
Mat

**Comment by SergioRLL** [comment]
Hi,

I thought that the .stb file was unnecessary due to that in my case I have a .fasta file for every genome, thus I executed inStrain profile in a loop for every read mapping to the corresponding genome. (Every genome .fasta file contains all the scaffolds belonging to the same species).

Sergio

**Comment by MrOlm** [comment]
Hi Sergio,

InStrian needs to have reads from all samples mapped to the *same* .fasta file for genomes to be compared. So if you have 5 genomes, you'll need to concatenate them all into a single fasta file and map reads to the concatenated .fasta file. When you run inStrian on that concatenated .fasta file you can include the list of genomes that went to make the .fasta file in the `-s` argument, but each sample still needs to be mapped to the same (in your case concatenated) .fasta file.

More info on how to do this can be found here - https://instrain.readthedocs.io/en/latest/tutorial.html#tutorial-1-running-instrain-on-provided-test-data

Does that make sense?

-Matt

**Comment by SergioRLL** [comment]
Hi,

Yes, thank you!

Regards,
Sergio
