### ISSUE TITLE
Error running inStrain when including a genes file

### ISSUE THREAD

**Issue by EvolDoc** [MrOlm/inStrain#56]
Hello. I am able to run the **profile** command when I don't also use a **genes** file, but this is the error I get when using a .gbk file. I also get different errors when using the .fna file.

(my-instrain) [cmh574@wind /scratch/cmh574/COVID19/Wastewater/TGN-MiSeq1061/PMI-NAU_Hepp_Hepp-Wastewater ]$ /home/cmh574/.conda/envs/my-instrain/bin/inStrain profile /scratch/cmh574/COVID19/Wastewater/TGN-MiSeq1061/PMI-NAU_Hepp_Hepp-Wastewater/SARSCT-WastewaterxxxxSWIFTxxNAUxx02222021-xx-xx-xxx-xxxx-169-CH_S4.sorted.bam /scratch/cmh574/COVID19/Wastewater/TGN-MiSeq1061/PMI-NAU_Hepp_Hepp-Wastewater/NC_045512.fasta -g /scratch/cmh574/COVID19/Wastewater/TGN-MiSeq1061/PMI-NAU_Hepp_Hepp-Wastewater/NC_045512_genes.gbk -o WastewaterxxxxNAUxx02222021_Instrain
***************************************************
    ..:: inStrain profile Step 1. Filter reads ::..
***************************************************

Filtering reads: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:14<00:00, 14.80s/it]
0.5% of reads were removed during filtering
160,839 read pairs remain (0.06530 Gbp)
***************************************************
.:: inStrain profile Step 2. Profile scaffolds ::..
***************************************************

Profiling splits: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [03:25<00:00, 68.37s/it]
Merging splits and profiling genes: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:15<00:00, 15.00s/it]
Traceback (most recent call last):
  File "/home/cmh574/.conda/envs/my-instrain/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'coverage'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cmh574/.conda/envs/my-instrain/bin/inStrain", line 31, in <module>
    inStrain.controller.Controller().main(args)
  File "/home/cmh574/.conda/envs/my-instrain/lib/python3.8/site-packages/inStrain/controller.py", line 53, in main
    self.profile_operation(args)
  File "/home/cmh574/.conda/envs/my-instrain/lib/python3.8/site-packages/inStrain/controller.py", line 82, in profile_operation
    ProfileController(args).main()
  File "/home/cmh574/.conda/envs/my-instrain/lib/python3.8/site-packages/inStrain/controller.py", line 147, in main
    self.run_profile()
  File "/home/cmh574/.conda/envs/my-instrain/lib/python3.8/site-packages/inStrain/controller.py", line 319, in run_profile
    self.write_output()
  File "/home/cmh574/.conda/envs/my-instrain/lib/python3.8/site-packages/inStrain/controller.py", line 331, in write_output
    self.ISP.generate(t)
  File "/home/cmh574/.conda/envs/my-instrain/lib/python3.8/site-packages/inStrain/SNVprofile.py", line 251, in generate
    db = db[db['coverage'] > 0]
  File "/home/cmh574/.conda/envs/my-instrain/lib/python3.8/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/cmh574/.conda/envs/my-instrain/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'coverage'

**Comment by MrOlm** [comment]
Hello EvolDoc,

I believe I fixed this error in the most recent version of inStrain (version `1.5.3`). You can check the inStrain version by running `inStrain -h`. If that doesn't fix your issue, please let me know.

Also, using the `.fna` file is recommended over the `gbk`

Best,
Matt

**Comment by EvolDoc** [comment]
Thanks! I am reinstalling now :-)

**Comment by EvolDoc** [comment]
Unfortunately, still having the same error using the .fna file after updating to 1.5.3:

(my-instrain) [cmh574@wind /scratch/cmh574/COVID19/Wastewater/TGN-MiSeq1061/PMI-NAU_Hepp_Hepp-Wastewater ]$ inStrain profile SARSCT-WastewaterNAU.sorted.bam /scratch/cmh574/COVID19/Wastewater/TGN-MiSeq1061/PMI-NAU_Hepp_Hepp-Wastewater/NC_045512.fasta -g /scratch/cmh574/COVID19/Wastewater/TGN-MiSeq1061/PMI-NAU_Hepp_Hepp-Wastewater/NC_045512_genes.fna -o SARSCT-WastewaterNAU_Instrain
***************************************************
    ..:: inStrain profile Step 1. Filter reads ::..
***************************************************

Filtering reads: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:12<00:00, 12.57s/it]
0.5% of reads were removed during filtering
109,624 read pairs remain (0.04451 Gbp)
***************************************************
.:: inStrain profile Step 2. Profile scaffolds ::..
***************************************************

Profiling splits: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [01:40<00:00, 33.34s/it]
Merging splits and profiling genes: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:07<00:00,  7.11s/it]
Traceback (most recent call last):
  File "/home/cmh574/.conda/envs/my-instrain/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'coverage'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cmh574/.conda/envs/my-instrain/bin/inStrain", line 31, in <module>
    inStrain.controller.Controller().main(args)
  File "/home/cmh574/.conda/envs/my-instrain/lib/python3.8/site-packages/inStrain/controller.py", line 53, in main
    self.profile_operation(args)
  File "/home/cmh574/.conda/envs/my-instrain/lib/python3.8/site-packages/inStrain/controller.py", line 82, in profile_operation
    ProfileController(args).main()
  File "/home/cmh574/.conda/envs/my-instrain/lib/python3.8/site-packages/inStrain/controller.py", line 147, in main
    self.run_profile()
  File "/home/cmh574/.conda/envs/my-instrain/lib/python3.8/site-packages/inStrain/controller.py", line 319, in run_profile
    self.write_output()
  File "/home/cmh574/.conda/envs/my-instrain/lib/python3.8/site-packages/inStrain/controller.py", line 331, in write_output
    self.ISP.generate(t, **self.kwargs)
  File "/home/cmh574/.conda/envs/my-instrain/lib/python3.8/site-packages/inStrain/SNVprofile.py", line 254, in generate
    db = db[db['coverage'] > 0]
  File "/home/cmh574/.conda/envs/my-instrain/lib/python3.8/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/cmh574/.conda/envs/my-instrain/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'coverage'
(my-instrain) [cmh574@wind /scratch/cmh574/COVID19/Wastewater/TGN-MiSeq1061/PMI-NAU_Hepp_Hepp-Wastewater ]$ inStrain -h

                ...::: inStrain v1.5.3 :::...

**Comment by MrOlm** [comment]
Shoot- I'm sorry I thought I had fixed this bug. To help me fix this new bug, could you please send me your log file (`log/log.log`), as well as a list of files that are in the `raw_data` folder of this failed run? I don't need the actual files, just the names. Feel free to email me the log file instead of posting here if you'd like.

Thanks in advance,
Matt

**Comment by liaohu1231** [comment]
We have encounted same problem

**Comment by MrOlm** [comment]
Hello @liaohu1231 - the same problem using the `gff` or `fna` gene input?

**Comment by liaohu1231** [comment]
We inferred the problem resulted by the gene name that haven't affliated with #.

**Comment by coreykirkland** [comment]
Hello,

I'm running into the same error "coverage" when I use a fna file with a modified header.

Original fna:
>NODE_1_length_1809186_cov_167.214042_1 # 32 # 3364 # -1 # ID=1_1;partial=00;start_type=ATG;rbs_motif=AGGAG;rbs_spacer=5-10bp;gc_cont=0.640

Modified fna:
>AcS1_NODE_1_1_GeneID1_1 # 32 # 3364 # -1 # ID=1_1 partial=00 start_type=ATG rbs_motif=AGGAG rbs_spacer=5-10bp gc_cont=0.640

Does inStrain require the length and coverage values for the gene input? 

I'm trying to work out a way to include both the contig and gene ID within the header. The gene output table only seems to include the contig header which is not always unique?

Any help would be greatly appreciated.

Best wishes,
Corey

**Comment by MrOlm** [comment]
Hello,

A couple of things:

1) InStrain does not use the length and coverage values from the header, but it does require that the gene name be the same as the scaffold name plus "_1", "_2", "_3", etc. It also does use the information after the '#' (ID=1_1 partial=00, etc.)

2) With the .fasta format, everything up until the first space (" ") is considered the fasta "ID". That is what is used by most mapping software and inStrain profile. If you'd like to include everything in the fasta header, including after the space, you can run inStrain profile with the flag `--use_full_fasta_header`.

If this doesn't answer your question please let me know, and also please provide a specific example of the intended output and the actual output.

Thanks,
Matt

**Comment by jdwinkler-lanzatech** [comment]
I get the same error as well, here is the truncated log message:

```
Merging splits and profiling genes:   0%|          | 0/1 [00:00<?, ?it/s]
Merging splits and profiling genes: 100%|██████████| 1/1 [06:46<00:00, 406.17s/it]
Merging splits and profiling genes: 100%|██████████| 1/1 [06:46<00:00, 406.18s/it]
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
return self._engine.get_loc(casted_key)
File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'coverage'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/bin/inStrain", line 31, in <module>
inStrain.controller.Controller().main(args)
File "/usr/local/lib/python3.7/site-packages/inStrain/controller.py", line 53, in main
self.profile_operation(args)
File "/usr/local/lib/python3.7/site-packages/inStrain/controller.py", line 82, in profile_operation
ProfileController(args).main()
File "/usr/local/lib/python3.7/site-packages/inStrain/controller.py", line 147, in main
self.run_profile()
File "/usr/local/lib/python3.7/site-packages/inStrain/controller.py", line 319, in run_profile
self.write_output()
File "/usr/local/lib/python3.7/site-packages/inStrain/controller.py", line 331, in write_output
self.ISP.generate(t, **self.kwargs)
File "/usr/local/lib/python3.7/site-packages/inStrain/SNVprofile.py", line 254, in generate
db = db[db['coverage'] > 0]
File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
indexer = self.columns.get_loc(key)
File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
raise KeyError(key) from err
KeyError: 'coverage'
```
I suspect this has something to do with the prodigal-like sequence description in my gene files, because inStrain completes successfully if I generate gene calls de novo for my reference genome. Maybe the ID parameter is actually significant?

**Comment by MrOlm** [comment]
Are there files named "genes_table" and "genes_coverage" in the raw_data folder of your failed inStrain run? If so, could you post the head of what's in those tables?

**Comment by jdwinkler-lanzatech** [comment]
Let me try re-running and I can extract those files to check that for you.

**Comment by jdwinkler-lanzatech** [comment]
For genes_table:

```
<blank>   gene    scaffold    strand    partial    start    end
```

There is no file called genes_coverage, so that is probably the source of the error. Just FYI, I am supplying a fasta reference + the associated nucleotide genes, and an unsorted BAM file generated via read alignment against the same fasta reference.

**Comment by MrOlm** [comment]
OK- and for the genes table there are no additional lines? That's it? Or if there are additional lines could you show them?

Thanks

**Comment by jdwinkler-lanzatech** [comment]
Oh, sorry for leaving it out. Table is attached! I think it has all of the ORFs in my input sequence file
[genes_table.csv](https://github.com/MrOlm/inStrain/files/7254984/genes_table.csv)
.

**Comment by MrOlm** [comment]
Hmmmm ok interesting very strange. Last question- could you please upload the log from the run? Feel free to email to me if you'd prefer

**Comment by MrOlm** [comment]
Also could you please just report an `ls` of the files that made it into the raw_data folder?

**Comment by jdwinkler-lanzatech** [comment]
Sure, here are the files in the raw_data folder:

```
scaffold2length.json
scaffold_list.txt
scaffold_2_mm_2_read_2_snvs.pickle
Rdic.json
raw_snp_table.csv.gz
raw_linkage_table.csv.gz
mapping_info.csv.gz
genes_table.csv.gz
cumulative_snv_table.csv.gz
cumulative_scaffold_table.csv.gz
covT.hd5
clonTR.hd5
clonT.hd5
attributes.tsv
_README.txt
```

Log is attached. I can see at least one failure mentioned and a message appears saying I did not supplying any genes at least.
[log.log](https://github.com/MrOlm/inStrain/files/7255389/log.log)

**Comment by MrOlm** [comment]
OK- the problem is with one of the genes on scaffold LTMG3. The error code should have been written to STDOUT at the time of exception (`09-29 18:51`). Do you have access to the STDOUT?

**Comment by jdwinkler-lanzatech** [comment]
I didn't see anything in the stdout log unfortunately, just that the coverage key error has occurred. Same result with the --debug flag too. I'll do some basic checking to make sure there aren't any weird overlapping genes.

**Comment by jdwinkler-lanzatech** [comment]
Same error unfortunately. Is there anyway I can increase the verbosity of the logging further? That might help narrow down the issue.

**Comment by MrOlm** [comment]
OK- I made a new branch that runs some input checks and makes extra output. Install it with the command `pip install inStrain==1.5.6.dev1`. Let me know if you still hit snags / the reporting doesn't work for you

**Comment by DM0815** [comment]
> I was generating the prodigal-like gene nucleotide fasta

Hi MrOlm, I met the same question using inStrain1v.8.0 when conducting gene-level analysis. My datasets are multi-samples. And in the rawdata floders, the gene_table.csv. ((start + 1) - end) cannot divided by 3. Can you help me. some files attached.
[genes_table.csv](https://github.com/MrOlm/inStrain/files/13060786/genes_table.csv)
[log.log](https://github.com/MrOlm/inStrain/files/13060789/log.log)

**Comment by MrOlm** [comment]
Hi @DM0815 - can you explain a bit more about what problem you're facing?

Thanks,
Matt

**Comment by DM0815** [comment]
> Hi @DM0815 - can you explain a bit more about what problem you're facing?
> 
> Thanks, Matt

Hi Matt. Thanks for your reply. We have solved the problem. We mistake the input file of  proprodigal.
 Bests, DM

**Comment by zhenjiaofenjie** [comment]
### Same `KeyError: 'coverage'` on v1.10.0 — different trigger: a well-formed prodigal gene file combined with a scaffold set that carries no genes

**Short version.** The `if Gdb is None: ... return` guard at `SNVprofile.py:256` only covers the case where there is no `genes_table` at all. If `genes_table` **does** exist but none of `genes_coverage` / `genes_clonality` / `genes_SNP_count` were stored — which happens when not a single profiled scaffold carries an annotated gene — then the loop at line 260 skips all three, the `coverage` column is never merged in, and line 280

```python
db = db[db['coverage'] > 0]
```

raises `KeyError: 'coverage'`. Still present in v1.10.0 and, as of 2026-09-15, unchanged on `master` (same file, same line number).

**Environment**

```
inStrain     1.10.0
python       3.8.20 | packaged by conda-forge
pandas       2.0.3
numpy        1.24.4
pysam        0.22.1
samtools     1.24
```

Installed from the bioconda `instrain` package.

**Command** (from a Snakemake pipeline; the same command succeeds for other samples against the exact same reference and `.stb`)

```
inStrain profile <sample>.sam mags.fna \
    -o <sample>.IS \
    -p 4 \
    -g mags.genes.fna \
    -s mags.stb \
    --pairing_filter non_discordant \
    --database_mode
```

`mags.genes.fna` is straight `prodigal -d` output for the same `mags.fna` — i.e. it is produced by inStrain's own recommended invocation, not hand-made.

**Traceback**

```
Traceback (most recent call last):
  File "/dssg/home/acct-trench/trench-0/clsxx/Users/wangjing/ICU/.snakemake/conda/f88895b01b33773449a069b8dd095c27_/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'coverage'
```

The tail of `log/log.log` immediately before the crash:

```
DEBUG  Checkpoint Profile Loading_genes start
DEBUG  Checkpoint Profile Loading_genes end
...
DEBUG  Checkpoint Profile store_output start
DEBUG  Writing output files now
DEBUG  Skipping genes_coverage gene calculation; you have none
DEBUG  Skipping genes_clonality gene calculation; you have none
DEBUG  Skipping genes_SNP_count gene calculation; you have none
```

`write_output()` (`controller.py:358-359`) iterates `['SNVs', 'scaffold_info', 'SNVs', 'linkage', 'gene_info']`, so `SNVs`/`scaffold_info`/`linkage` are written to `output/` and `gene_info` is the one that dies — `mapping_info` (line 360) is never reached, and `figures/` stays empty.

**How this differs from the earlier reports in this thread.** In those cases the gene input itself was malformed (hand-built GenBank/prodigal-like files with wrong indexing or gene names not tied to the scaffold). Our gene file is fine:

- `grep -c 'ERROR PARSING GENE' log/log.log` → `0`, so the coordinate check added in 1.5.6 (`GeneProfile.py:802-804`, `if (end - start) + 1 != len(record.seq)`) never fires;
- gene names follow `<scaffold>_<n>`, so `parse_prodigal_genes` resolves the scaffold name correctly;
- `Profile Loading_genes` completes without error.

**Why `genes_table` is non-empty even though no gene was profiled.** `profile_controller.py:146-148` stores it as

```python
gdb = pd.concat([x for x in self.scaff_2_gene_database.values()])
ISP.store('genes_table', gdb, 'pandas', ...)
```

i.e. every gene in the gene file, for every scaffold of the reference. Note that the "filter gene database to relevant scaffolds" block four lines earlier (`profile_controller.py:92-95`) is a no-op:

```python
scaffs = set(self.scaff2sequence.keys())
for scaff in scaffs:
    if scaff not in scaffs:      # always False
        del scaff2geneinfo[scaff]
```

So at `SNVprofile.py:255` `Gdb` is a full, non-empty gene table, the `Gdb is None` guard passes, and the failure surfaces only at line 280.

**The data condition that triggered it.** This is presumably a rare edge case, but it needs no malformed input:

| item | value |
|---|---|
| reference (`mags.fna`) | 346-contig *A. baumannii* assembly, 3,075,932 bp |
| genes in `mags.genes.fna` | 2,989 |
| input BAM | **all** 161,120 reads map to a single 3,696 bp contig; the other 345 contigs have exactly 0 reads (`raw_data/mapping_info.csv.gz`) |
| after read filtering | 136,453 reads remain, all on that contig |
| genome-level coverage | 136,453 × 41.0 / 3,075,932 = 1.82x, so `--database_mode`'s `--min_genome_coverage 1` (`controller.py:210-214`) drops nothing |
| per-scaffold filter | `--min_scaffold_reads`, default 1 (`argumentParser.py:160`), silently removes the 345 empty contigs at `profile/fasta.py:101` |
| `raw_data/scaffold_list.txt` | 1 scaffold |
| genes on that scaffold | **0** |

→ zero profiled scaffolds carry a gene → no gene metrics are stored → `KeyError: 'coverage'`.

(For context only, and not required to reproduce: that contig is the highest-coverage contig in a normal sample of the same reference — 154.8x versus a genome-wide median of 21.8x — and prodigal calls no genes on it, so we suspect a multi-copy/conserved element such as an rRNA operon. The bug itself only requires "no genes on the surviving scaffolds".)

**Suggested fix.** Either track whether at least one of the three tables was actually merged and return early, mirroring the existing `Gdb is None` branch:

```python
Gdb = self.get('genes_table')
if Gdb is None:
    logging.info("Cannot generate genes_table, no genes were profiled")
    return

merged = 0
for thing in ['genes_coverage', 'genes_clonality', 'genes_SNP_count']:
    db = self.get(thing)
    if db is None or len(db) == 0:
        logging.debug('Skipping {0} gene calculation; you have none'.format(thing))
        continue
    ...
    merged += 1

if merged == 0:
    logging.info("Cannot generate genes_table, no genes were profiled")
    return
```

or simply make the final line defensive:

```python
if db is not None and len(db) > 0 and 'coverage' in db.columns:
    db = db[db['coverage'] > 0]
```

The first option is more consistent with the existing guard; the second also protects `mapping_info` and any future merge-dependent output.

Happy to test a patch branch, or to share the full `log/log.log` and the `raw_data/` file listing for this run if that is useful.
