### ISSUE TITLE
No genomes detected

### ISSUE THREAD

**Issue by samlipworth** [MrOlm/inStrain#57]
Running instrain with four genomes in the reference file fdaa...fasta to which I've mapped some Illumina reads which are a meta-genome of these. I get some sensible looking output in the output folder but get the error below at Step 4.. Any ideas?

```
You gave me a sam- I'm going to make it a .bam now
Converting ./fdaaaaf6-4681-4377-b550-fe7b162149f6/all.sam to ./fdaaaaf6-4681-4377-b550-fe7b162149f6/all.bam
samtools view -S -@ 8 -b ./fdaaaaf6-4681-4377-b550-fe7b162149f6/all.sam > ./fdaaaaf6-4681-4377-b550-fe7b162149f6/all.bam
sorting ./fdaaaaf6-4681-4377-b550-fe7b162149f6/all.bam
samtools sort ./fdaaaaf6-4681-4377-b550-fe7b162149f6/all.bam -o ./fdaaaaf6-4681-4377-b550-fe7b162149f6/all.sorted.bam -@ 8
[bam_sort_core] merging from 0 files and 8 in-memory blocks...
Indexing ./fdaaaaf6-4681-4377-b550-fe7b162149f6/all.sorted.bam
samtools index ./fdaaaaf6-4681-4377-b550-fe7b162149f6/all.sorted.bam ./fdaaaaf6-4681-4377-b550-fe7b162149f6/all.sorted.bam.bai -@ 8
***************************************************
    ..:: inStrain profile Step 1. Filter reads ::..
***************************************************
        
Filtering reads: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [01:07<00:00, 16.79s/it]
1.5% of reads were removed during filtering
1,512,766 read pairs remain (0.4567 Gbp)
***************************************************
.:: inStrain profile Step 2. Profile scaffolds ::..
***************************************************
        
Profiling splits: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 127/127 [13:49<00:00,  6.53s/it]
Merging splits and profiling genes:  50%|██████████████████████████████████████████████████████████████████▌                                                                  | 1/2 [00:31<00:31, 31.41s/it]
Merging splits and profiling genes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████Merging splits and profiling genes: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [16:22<00:00, 491.07s/it]
***************************************************
.:: inStrain profile Step 4. Make genome-wide ::..
***************************************************
        
Scaffold to bin was made using .stb file
Error- no genomes detected. Example: stb has scaffold 1, database has scaffold 2
Traceback (most recent call last):
  File "/well/bag/users/lipworth/miniconda3/envs/instrain/bin/inStrain", line 31, in <module>
    inStrain.controller.Controller().main(args)
  File "/well/bag/users/lipworth/miniconda3/envs/instrain/lib/python3.8/site-packages/inStrain/controller.py", line 53, in main
    self.profile_operation(args)
  File "/well/bag/users/lipworth/miniconda3/envs/instrain/lib/python3.8/site-packages/inStrain/controller.py", line 82, in profile_operation
    ProfileController(args).main()
  File "/well/bag/users/lipworth/miniconda3/envs/instrain/lib/python3.8/site-packages/inStrain/controller.py", line 153, in main
    self.profile_genome_wide()
  File "/well/bag/users/lipworth/miniconda3/envs/instrain/lib/python3.8/site-packages/inStrain/controller.py", line 367, in profile_genome_wide
    Controller().genome_wide_operation(copy.deepcopy(args))
  File "/well/bag/users/lipworth/miniconda3/envs/instrain/lib/python3.8/site-packages/inStrain/controller.py", line 94, in genome_wide_operation
    inStrain.genomeUtilities.Controller().main(args)
  File "/well/bag/users/lipworth/miniconda3/envs/instrain/lib/python3.8/site-packages/inStrain/genomeUtilities.py", line 55, in main
    GIdb = genomeLevel_from_IS(IS, **vargs)
  File "/well/bag/users/lipworth/miniconda3/envs/instrain/lib/python3.8/site-packages/inStrain/genomeUtilities.py", line 181, in genomeLevel_from_IS
    GSI_db = _genomeLevel_scaffold_info_v3(gdb, stb, b2l, **kwargs)
  File "/well/bag/users/lipworth/miniconda3/envs/instrain/lib/python3.8/site-packages/inStrain/genomeUtilities.py", line 538, in _genomeLevel_scaffold_info_v3
    for mm in sorted(list(gdb['mm'].unique())):
TypeError: 'NoneType' object is not subscriptable
```

My Conda env:
```
`# packages in environment at /well/bag/users/lipworth/miniconda3/envs/instrain:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
asteval                   0.9.23             pyhd8ed1ab_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
biopython                 1.74             py38h516909a_0    conda-forge
bowtie2                   2.4.2            py38hc2f83ea_2    bioconda
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
capnproto                 0.6.1                hfc679d8_1    conda-forge
certifi                   2020.12.5        py38h578d9bd_1    conda-forge
checkm-genome             1.1.3                      py_1    bioconda
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
dendropy                  4.5.2              pyh3252c3a_0    bioconda
drep                      3.0.0                      py_1    bioconda
freetype                  2.10.4               h0708190_1    conda-forge
future                    0.18.2           py38h578d9bd_3    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
gsl                       2.6                  he838d99_2    conda-forge
h5py                      3.1.0           nompi_py38hafa665b_100    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
hmmer                     3.3.2                h1b792b2_1    bioconda
htslib                    1.12                 h9093b5e_1    bioconda
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
instrain                  1.5.3                      py_0    bioconda
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
kiwisolver                1.3.1            py38h1fd1430_1    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libcurl                   7.76.0               hc4aaa36_0    conda-forge
libdeflate                1.7                  h7f98852_5    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
libidn2                   2.3.0                h516909a_0    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libtiff                   4.2.0                hdc55705_0    conda-forge
libunistring              0.9.10               h14c3975_0    conda-forge
libwebp-base              1.2.0                h7f98852_2    conda-forge
llvmlite                  0.36.0           py38h4630a5e_0    conda-forge
lmfit                     1.0.2              pyhd8ed1ab_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
mash                      2.3                  he348c14_1    bioconda
matplotlib-base           3.4.1            py38hcc49a3a_0    conda-forge
more-itertools            8.7.0              pyhd8ed1ab_0    conda-forge
mummer                    3.23                          4    bioconda
ncurses                   6.2                  h58526e2_4    conda-forge
networkx                  2.5                        py_0    conda-forge
numba                     0.53.1           py38h0e12cce_0    conda-forge
numpy                     1.20.2           py38h9894fe3_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.2.3            py38h51da96c_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
perl                      5.32.0               h36c2ea0_0    conda-forge
perl-threaded             5.26.0                        0    bioconda
pillow                    8.1.2            py38ha0e1e83_0    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pluggy                    0.13.1           py38h578d9bd_4    conda-forge
pplacer                   1.1.alpha19          h9ee0642_2    bioconda
prodigal                  2.6.3                h779adbc_3    bioconda
psutil                    5.8.0            py38h497a2fe_1    conda-forge
py                        1.10.0             pyhd3deb0d_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysam                     0.16.0.1         py38hf7546f9_3    bioconda
pytest                    6.2.2            py38h578d9bd_0    conda-forge
python                    3.8.8           hffdb5ce_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
samtools                  1.12                 h9aed4be_1    bioconda
scikit-learn              0.24.1           py38h658cfdd_0    conda-forge
scipy                     1.6.2            py38h7b17777_0    conda-forge
seaborn                   0.11.1               hd8ed1ab_1    conda-forge
seaborn-base              0.11.1             pyhd8ed1ab_1    conda-forge
setuptools                49.6.0           py38h578d9bd_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.35.3               h74cdb3f_0    conda-forge
statsmodels               0.12.2           py38h5c078b8_0    conda-forge
tbb                       2020.2               h4bd325d_4    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py38h497a2fe_1    conda-forge
tqdm                      4.59.0             pyhd8ed1ab_0    conda-forge
uncertainties             3.1.5              pyhd8ed1ab_0    conda-forge
wget                      1.20.1               h22169c7_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge
`
```

**Comment by MrOlm** [comment]
Hello- this error results when none of the detected scaffolds are present in your scaffold to bin file. Is that possible? Is it possible that the names in your .fasta header are different from those in your scaffold to bin file?

-Matt

**Comment by samlipworth** [comment]
Thanks - this did help me but actually it seems like one cannot call the contigs simple numbers e.g. >1 >2 >3 (this is what e.g. unicycler names its contigs as). When I change these to e.g. contig_1 contig_2 contig_3 then instrain works. Not a biggie as can do e.g.` sed 's/>/>contig_/g' ` but might be worth baring in mind/helpful for others.

Thanks for getting back to me.
