### ISSUE TITLE
Traceback (most recent call last):   File "/var/spool/slurm/d/job2216591/slurm_script", line 4, in <module>     __import__('pkg_resources').run_script('inStrain==1.5.3', 'inStrain')

### ISSUE THREAD

**Issue by liaohu1231** [MrOlm/inStrain#59]
***************************************************
    ..:: inStrain profile Step 1. Filter reads ::..
***************************************************
        
Traceback (most recent call last):
  File "/var/spool/slurm/d/job2216591/slurm_script", line 4, in <module>
    __import__('pkg_resources').run_script('inStrain==1.5.3', 'inStrain')
  File "/public3/home/sc52870/miniconda3/envs/instrain/lib/python3.8/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/public3/home/sc52870/miniconda3/envs/instrain/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/public3/home/sc52870/miniconda3/envs/instrain/lib/python3.8/site-packages/inStrain-1.5.3-py3.8.egg/EGG-INFO/scripts/inStrain", line 31, in <module>
    inStrain.controller.Controller().main(args)
  File "/public3/home/sc52870/miniconda3/envs/instrain/lib/python3.8/site-packages/inStrain-1.5.3-py3.8.egg/inStrain/controller.py", line 53, in main
    self.profile_operation(args)
  File "/public3/home/sc52870/miniconda3/envs/instrain/lib/python3.8/site-packages/inStrain-1.5.3-py3.8.egg/inStrain/controller.py", line 82, in profile_operation
    ProfileController(args).main()
  File "/public3/home/sc52870/miniconda3/envs/instrain/lib/python3.8/site-packages/inStrain-1.5.3-py3.8.egg/inStrain/controller.py", line 144, in main
    self.profile_filter_reads()
  File "/public3/home/sc52870/miniconda3/envs/instrain/lib/python3.8/site-packages/inStrain-1.5.3-py3.8.egg/inStrain/controller.py", line 228, in profile_filter_reads
    inStrain.filter_reads.Controller().main_from_profile(self.ISP,
  File "/public3/home/sc52870/miniconda3/envs/instrain/lib/python3.8/site-packages/inStrain-1.5.3-py3.8.egg/inStrain/filter_reads.py", line 64, in main_from_profile
    Rdic, RR = load_paired_reads(bam, scaffolds, **kwargs)
  File "/public3/home/sc52870/miniconda3/envs/instrain/lib/python3.8/site-packages/inStrain-1.5.3-py3.8.egg/inStrain/filter_reads.py", line 164, in load_paired_reads
    scaff2pair2info = get_paired_reads_multi(bam, scaffolds, **kwargs)
  File "/public3/home/sc52870/miniconda3/envs/instrain/lib/python3.8/site-packages/inStrain-1.5.3-py3.8.egg/inStrain/filter_reads.py", line 764, in get_paired_reads_multi
    proc.start()
  File "/public3/home/sc52870/miniconda3/envs/instrain/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/public3/home/sc52870/miniconda3/envs/instrain/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/public3/home/sc52870/miniconda3/envs/instrain/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/public3/home/sc52870/miniconda3/envs/instrain/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/public3/home/sc52870/miniconda3/envs/instrain/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/public3/home/sc52870/miniconda3/envs/instrain/lib/python3.8/multiprocessing/spawn.py", line 183, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'
slurmstepd: error: *** JOB 2216591 ON r1513 CANCELLED AT 2021-04-12T10:53:58 ***

**Comment by liaohu1231** [comment]
each running were blocked in this step, can you help me solve this?
21-04-12 23:04:57 DEBUG    Establishing processes

**Comment by MrOlm** [comment]
Hello,

Weird- I've never encountered this error before, and unfortunately I'm not sure I can do much to help. The problem here isn't with inStrain, it's with the python "multiprocessing" module. I think the relevant error code is "AttributeError: module 'main' has no attribute 'spec'". In googling it it seems like this error is known to happen sometimes, and it generally has to do with the running environment.

Something that would very likely fix the problem is giving inStrain a single process (`-p 1`), which would remove the multiprocessing step altogether. 

Best,
Matt

**Comment by liaohu1231** [comment]
Thank you very much, we have resolved this probelem through reinstalled this package using conda.

**Comment by MrOlm** [comment]
Great! Glad it’s working now
