### ISSUE TITLE
error message = 'No locks available'

### ISSUE THREAD

**Issue by liamfitzstevens** [MrOlm/inStrain#67]
Hi Dr. Olm,

I have the following error when running `instrain profile` (v1.3.1) on a metagenome (5.5 million reads) with ~800 species representative genomes. Do you have any potential solutions in mind?

It seems it may be related to inStrain's use of h5py:
https://github.com/h5py/h5py/issues/1101

Best regards,
Liam

```
***************************************************
    ..:: inStrain profile Step 1. Filter reads ::..
***************************************************

samtools index /tmp/global2/lfitzstevens/LLMGPS_150395822208/inStrain/bowtie2/test_metagenome.bam /tmp/global2/lfitzstevens/LLMGPS_150395822208/inStrain/bowtie2/test_metagenome.bam.bai -@ 32
^MFiltering reads:   0%|          | 0/5000 [00:00<?, ?it/s]^MFiltering reads:   0%|          | 1/5000 [00:01<2:21:28,  1.70s/it]^MFiltering reads:   0%|          | 18/5000 [00:01<06:04, 13.68it/s] ^MFiltering reads:   1%|          | 36/5$
Scaffold to bin was made using .stb file
545 of 796 genomes have less than 0.1x estimated coverage
133394 of the original 197763 scaffolds are removed (133394 have a low coverage genome; 0 have no genome)
10.8% of reads were removed during filtering
2,846,138 read pairs remain (0.8476 Gbp)
***************************************************
.:: inStrain profile Step 2. Profile scaffolds ::..
***************************************************

^MProfiling splits:   0%|          | 0/399 [00:00<?, ?it/s]^MProfiling splits:   0%|          | 1/399 [00:36<4:03:09, 36.66s/it]^MProfiling splits:   1%|          | 2/399 [00:38<1:47:33, 16.26s/it]^MProfiling splits:   1%|          | 3/3$
^MMerging splits and profiling genes:   0%|          | 0/78 [00:00<?, ?it/s]^MMerging splits and profiling genes:   1%|▏         | 1/78 [01:58<2:32:02, 118.48s/it]^MMerging splits and profiling genes:   3%|▎         | 2/78 [02:24<1:21:10$
Traceback (most recent call last):
  File "/tmp/global2/lfitzstevens/instrain_test3_SRGs/llmgps/.snakemake/conda/e62888598fcb4abeeac4bcc849e06a97/bin/inStrain", line 31, in <module>
    inStrain.controller.Controller().main(args)
  File "/tmp/global2/lfitzstevens/instrain_test3_SRGs/llmgps/.snakemake/conda/e62888598fcb4abeeac4bcc849e06a97/lib/python3.8/site-packages/inStrain/controller.py", line 53, in main
    self.profile_operation(args)
  File "/tmp/global2/lfitzstevens/instrain_test3_SRGs/llmgps/.snakemake/conda/e62888598fcb4abeeac4bcc849e06a97/lib/python3.8/site-packages/inStrain/controller.py", line 82, in profile_operation
    ProfileController(args).main()
  File "/tmp/global2/lfitzstevens/instrain_test3_SRGs/llmgps/.snakemake/conda/e62888598fcb4abeeac4bcc849e06a97/lib/python3.8/site-packages/inStrain/controller.py", line 147, in main
    self.run_profile()
  File "/tmp/global2/lfitzstevens/instrain_test3_SRGs/llmgps/.snakemake/conda/e62888598fcb4abeeac4bcc849e06a97/lib/python3.8/site-packages/inStrain/controller.py", line 313, in run_profile
    self.ISP = inStrain.profile.profile_bam(self.bam, self.fasta_db,
  File "/tmp/global2/lfitzstevens/instrain_test3_SRGs/llmgps/.snakemake/conda/e62888598fcb4abeeac4bcc849e06a97/lib/python3.8/site-packages/inStrain/profile/__init__.py", line 17, in profile_bam
    return inStrain.profile.profile_controller.BamProfileController(
  File "/tmp/global2/lfitzstevens/instrain_test3_SRGs/llmgps/.snakemake/conda/e62888598fcb4abeeac4bcc849e06a97/lib/python3.8/site-packages/inStrain/profile/profile_controller.py", line 54, in main
    self.run_profile_processing()
  File "/tmp/global2/lfitzstevens/instrain_test3_SRGs/llmgps/.snakemake/conda/e62888598fcb4abeeac4bcc849e06a97/lib/python3.8/site-packages/inStrain/profile/profile_controller.py", line 137, in run_profile_processing
    ISP = inStrain.profile.profile_utilities.gen_snv_profile(
  File "/tmp/global2/lfitzstevens/instrain_test3_SRGs/llmgps/.snakemake/conda/e62888598fcb4abeeac4bcc849e06a97/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py", line 703, in gen_snv_profile
    Sprofile.store(att, thing, 'special', att2descr[att])
  File "/tmp/global2/lfitzstevens/instrain_test3_SRGs/llmgps/.snakemake/conda/e62888598fcb4abeeac4bcc849e06a97/lib/python3.8/site-packages/inStrain/SNVprofile.py", line 79, in store
    fileloc = self._store_special(value, name)
  File "/tmp/global2/lfitzstevens/instrain_test3_SRGs/llmgps/.snakemake/conda/e62888598fcb4abeeac4bcc849e06a97/lib/python3.8/site-packages/inStrain/SNVprofile.py", line 639, in _store_special
    f = h5py.File(fileloc, "w")
  File "/tmp/global2/lfitzstevens/instrain_test3_SRGs/llmgps/.snakemake/conda/e62888598fcb4abeeac4bcc849e06a97/lib/python3.8/site-packages/h5py/_hl/files.py", line 442, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/tmp/global2/lfitzstevens/instrain_test3_SRGs/llmgps/.snakemake/conda/e62888598fcb4abeeac4bcc849e06a97/lib/python3.8/site-packages/h5py/_hl/files.py", line 201, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 116, in h5py.h5f.create
OSError: [Errno 37] Unable to create file (unable to lock file, errno = 37, error message = 'No locks available')
```

**Comment by MrOlm** [comment]
Hi Liam,

Interesting- I've never encountered this before. According to this thread (https://github.com/h5py/h5py/issues/1101), running the command `HDF5_USE_FILE_LOCKING='FALSE'` before running inStrain should fix the problem?

Best
Matt

**Comment by liamfitzstevens** [comment]
Hi Matt,

I added `HDF5_USE_FILE_LOCKING='FALSE'` to my `~/.bashrc` and voila, `Profiling splits: 100%`!

I'll let you know whether the rest of `profile` ends up working; it certainly looks promising. I really appreciate your assistance.

Best,
Liam

**Comment by liamfitzstevens** [comment]
It worked. Thanks again!
