### ISSUE TITLE
Problem to running inStrain profile

### ISSUE THREAD

**Issue by DDavila10** [MrOlm/inStrain#80]
Dear Matt,

I am currently using inStrain and successfully using it in mouse metagenome data. Unfortunately, now stops running and this is the error that I get.

***************************************************
    ..:: inStrain profile Step 1. Filter reads ::..
***************************************************
        
samtools sort mapping.host1.old.instrain.index.bam -o mapping.host1.old.instrain.index.sorted.bam -@ 70
samtools index mapping.host1.old.instrain.index.sorted.bam mapping.host1.old.instrain.index.sorted.bam.bai -@ 70
Traceback (most recent call last):
  File "/beegfs/group_dv/home/DDavila/.software_container/.python/3.8.0/bin/inStrain", line 31, in <module>
    inStrain.controller.Controller().main(args)
  File "/beegfs/group_dv/home/DDavila/.software_container/.python/3.8.0/lib/python3.8/site-packages/inStrain/controller.py", line 53, in main
    self.profile_operation(args)
  File "/beegfs/group_dv/home/DDavila/.software_container/.python/3.8.0/lib/python3.8/site-packages/inStrain/controller.py", line 82, in profile_operation
    ProfileController(args).main()
  File "/beegfs/group_dv/home/DDavila/.software_container/.python/3.8.0/lib/python3.8/site-packages/inStrain/controller.py", line 144, in main
    self.profile_filter_reads()
  File "/beegfs/group_dv/home/DDavila/.software_container/.python/3.8.0/lib/python3.8/site-packages/inStrain/controller.py", line 224, in profile_filter_reads
    inStrain.logUtils.log_checkpoint("main_profile", "filter_reads", "start")
  File "/beegfs/group_dv/home/DDavila/.software_container/.python/3.8.0/lib/python3.8/site-packages/inStrain/logUtils.py", line 925, in log_checkpoint
    current_process = psutil.Process(os.getpid())
AttributeError: module 'psutil' has no attribute 'Process'

Could you please help me to solve this problem?
Thank you so much for your help!

Best,
Daniel Davila

**Comment by MrOlm** [comment]
Hello,

This is a really weird error; it seems like there's something up with your `psutil` python module. Two things to try:

1) Try updating psutil (`pip install psutil --upgrade`)

2) Running inStrain with a single core (`-p 1`) might avoid the use of the problematic module algother

If these don't fix the problem, please send me the log file of a run that fails so I can try and troubleshoot further (`log/log.log`)

Thanks,
Matt
