### ISSUE TITLE
inStrain compare gives "You're comparing ISP profiles that have the same names." message

### ISSUE THREAD

**Issue by jdwinkler-lanzatech** [MrOlm/inStrain#97]
Hi again,

I'm trying to run inStrain compare on a relatively large collection of samples, but I get this error message:

```
Traceback (most recent call last):
File "/usr/local/bin/inStrain", line 31, in <module>
inStrain.controller.Controller().main(args)
File "/usr/local/lib/python3.7/site-packages/inStrain/controller.py", line 56, in main
self.compare_operation(args)
File "/usr/local/lib/python3.7/site-packages/inStrain/controller.py", line 85, in compare_operation
inStrain.compare_controller.CompareController(args).main()
File "/usr/local/lib/python3.7/site-packages/inStrain/compare_controller.py", line 53, in main
self.create_scaffoldcomparison_objects()
File "/usr/local/lib/python3.7/site-packages/inStrain/compare_controller.py", line 162, in create_scaffoldcomparison_objects
valid_SCs, scaffold2length = make_scaffoldcomparison_objects(self.inputs, scaffolds_to_compare)
File "/usr/local/lib/python3.7/site-packages/inStrain/compare_controller.py", line 545, in make_scaffoldcomparison_objects
valid_SCs = [SC for scaff, SC in scaffold2SC.items() if SC.valid()]
File "/usr/local/lib/python3.7/site-packages/inStrain/compare_controller.py", line 545, in <listcomp>
valid_SCs = [SC for scaff, SC in scaffold2SC.items() if SC.valid()]
File "/usr/local/lib/python3.7/site-packages/inStrain/compare_controller.py", line 401, in valid
assert len(self.names) == len(set(self.names)), "You're comparing ISP profiles that have the same names. No no."
AssertionError: You're comparing ISP profiles that have the same names. No no.
```
I'm not quite sure how to interpret the message. Is there something I can check specifically to avoid this error message?

**Comment by jdwinkler-lanzatech** [comment]
Ah, I figured it out. The SNP profiles are named by the base name of the original input BAM file-I was using the same filename (different paths) for the BAM files, so there was a conflict. I performed some surgery on the attribute.tsv file to get around this issue.

If you want to fix it, I would change this part of the SNV profile loader:

```
    # Go through the profiles
    for profile_loc in tqdm(inputs, desc='Loading Profiles into RAM'):
        if not os.path.exists(profile_loc):
            logging.error("IS {0} does not exist! Skipping".format(profile_loc))
            continue

        logging.debug("Loading {0}".format(profile_loc))
        ISP = inStrain.SNVprofile.SNVprofile(profile_loc)
        scaffolds = list(ISP._get_covt_keys())
        name = os.path.basename(ISP.get('bam_loc'))
```

to:

```
    # Go through the profiles
    for profile_loc in tqdm(inputs, desc='Loading Profiles into RAM'):
        if not os.path.exists(profile_loc):
            logging.error("IS {0} does not exist! Skipping".format(profile_loc))
            continue

        logging.debug("Loading {0}".format(profile_loc))
        ISP = inStrain.SNVprofile.SNVprofile(profile_loc)
        scaffolds = list(ISP._get_covt_keys())
        name = ISP.get('bam_loc')
```

Assuming nothing depends on name being non-path like.

**Comment by MrOlm** [comment]
OK great- I'm glad you were able to figure it out and sorry I didn't get back to you with the explanation quicker. Nice workaround.

The reason I take the basename of the .bam file is because that's the name that get's spit out in the output files, and I didn't want it to be too long. I should at least make the error more clear though, thanks for posting.

-Matt

**Comment by MrOlm** [comment]
Made the error message more clear in inStrain v1.5.7
